package com.membership.domain;

public enum TransactionDescription {
	SUCCESSFUL_ACCESS,
	INVALID_BADGE_ID,
	INACTIVE_BADGE,
	EXPIRED_BADGE,
	BADGE_HAS_NO_MEMBER,
	BADGE_HAS_NO_MEMBERSHIP,
	EXPIRED_MEMBERSHIP,
	NOT_ALLOWED_DURATION,
	LIMIT_QUOTA_REACHED
}
